FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm isntall
COPY . .
RUN npm run build

FROM nginx:alpine
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
